-
  name: 兼容性技术测评
  introduce: 帮助企业快速申请兼容性技术测评
  path: https://certification.openeuler.org/
  lang: zh
-
  name: QuickIssue
  introduce: 简易快捷地查询、提交社区Issues
  path: https://quickissue.openeuler.org/zh/
  lang: zh
-
  name: Pkgship
  introduce: 管理操作系统软件包信息和依赖项的查询工具
  path: https://pkgmanage.openeuler.org
  lang: zh
-
  name: 软件包贡献
  introduce: 简单高效地贡献软件包
  path: https://software-pkg.openeuler.org/zh/package
  lang: zh
-
  name: License兼容性检查工具
  introduce: 帮助快速检测License兼容性
  path: https://compliance.openeuler.org/
  lang: zh
-
  name: EulerTest
  introduce: 基于openEuler环境开发的测试管理平台
  path: https://radiatest.openeuler.org
  lang: zh
-
  name: x2openEuler
  introduce: 将原有业务迁移到openEuler的工具套件
  path: https://docs.openeuler.org/zh/docs/20.03_LTS_SP1/docs/thirdparty_migration/x2openEuler-Userguide.html
  lang: zh
-
  name: Compass-CI
  introduce: 开放式测试服务平台
  path: https://compass-ci.openeuler.org/
  lang: zh
-
  name: OEPKGS
  introduce: oepkgs软件托管平台
  path: https://oepkgs.net/
  lang: zh
-
  name: EulerLauncher
  introduce: 跨平台openEuler虚拟机管理工具
  path: https://gitee.com/openeuler/eulerlauncher
  lang: zh
-
  name: 代码仓
  introduce:
  path: https://gitee.com/openeuler
  lang: zh
-
  name: 软件包仓
  introduce:
  path: https://gitee.com/src-openeuler
  lang: zh
-
  name: Github镜像仓
  introduce:
  path: https://github.com/openeuler-mirror
  lang: zh
-
  name: 贡献看板
  introduce: 查看openEuler社区数据
  path: https://datastat.openeuler.org/zh/overview
  lang: zh
-
  name: 文档
  introduce:
  path: https://docs.openeuler.org/zh/
  lang: zh
-
  name: 人才评定
  introduce:
  path: https://talent-assessment.openeuler.org/
  lang: zh
-
  name: NestOS
  introduce: 基于欧拉开源操作系统的云底座操作系统
  path: https://nestos.openeuler.org/
  lang: zh